# Generated by Django 3.2.13 on 2022-06-21 22:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ciara0s1980/image/upload/v1655849315/default__image.webp', max_length=255, verbose_name='image'),
        ),
    ]
