# Generated by Django 3.2.13 on 2022-07-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='other_relevant_information',
        ),
    ]
